package com.sam.rabbitmq.webapp.response;

public interface ResponseCodes {
	Integer INVALID_POST_DATA=100;
	Integer MOBILE_NUMBER_REQUIRED=101;
	Integer EMAIL_ID_REQUIRED=102;
	Integer MOBILE_NUM_OR_EMAIL_ID_REQUIRED=103;
	Integer FIRST_NAME_REQUIRED=104;
	Integer LAST_NAME_REQUIRED=105;
	Integer MOBILE_NUMBER_ALREADY_EXISTS=106;
	Integer EMAIL_ID_ALREADY_EXISTS=107;
	Integer PASSWORD_REQUIRED=108;
	Integer INVALID_CREDENTIALS=109;
	Integer MOBILE_NUM_SHOULD_BE_10_DIGIT_LONG = 110;
	Integer INVALID_EMAIL_ID = 111;
	Integer REGISTRATION_SUCCESS = 112;
	Integer SYSTEM_ERROR = 501;
	Integer LOGIN_SUCCESS = 113;
	Integer SUCCESS = 200;
	Integer SESSION_ID_REQUIRED = 114;
	Integer INVALID_SESSION_ID = 115;
	Integer INVALID_REC_USER_ID = 116;
	Integer INVALID_STATUS = 117;
	
}
